"""One-command launcher.

Boots the hidden ComfyUI engine as a subprocess, waits until it is healthy, then serves the
CHNMagicAI web app and opens the browser. Run this with the vendored Python:

    engine/python/python.exe backend/launcher.py      (or use run.bat)
"""
import asyncio
import json
import os
import subprocess
import sys
import threading
import time
import webbrowser

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CONFIG_PATH = os.path.join(ROOT, "config", "settings.json")
LOCAL_CONFIG_PATH = os.path.join(ROOT, "config", "settings.local.json")


def phase(pct, msg):
    """Emit a machine-readable progress anchor for the Electron splash, plus a human line.

    The splash parses `AIVB_PHASE|<pct>|<message>` from stdout; the streaming [setup]/[launcher]
    lines fill in the detail message between anchors."""
    print(f"AIVB_PHASE|{pct}|{msg}", flush=True)


def load_settings():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        settings = json.load(f)
    # Per-machine overrides (git-ignored): python_exe, model paths, etc.
    if os.path.isfile(LOCAL_CONFIG_PATH):
        with open(LOCAL_CONFIG_PATH, "r", encoding="utf-8") as f:
            settings.update(json.load(f))
    sys.path.insert(0, os.path.dirname(__file__))
    import env as env_mod
    env_mod.apply(settings)
    return settings


def _located_model_dirs(models_dir, settings):
    """Where 'located'/overridden model files actually live, so the engine can also search there.

    A user can point the app at an already-downloaded model ("Locate existing"); the source is
    recorded in settings.model_overrides. Normally the file is also hard-linked into `models_dir`,
    but that link lives in whichever data dir was active at the time. When a *different* data dir is
    used later (the desktop app's %APPDATA% tree, RunPod's /workspace) `models_dir` can be empty even
    though the files exist elsewhere — the engine then rejects the graph with "<name> not in []".
    Registering the real folders here makes the basenames resolve regardless of the active data dir.

    Returns (roots, extra) where `roots` are standard `<root>/<subfolder>/<file>` layout roots (mapped
    with the full subfolder list, like the primary provider) and `extra` maps a category -> dirs for
    any file that isn't in a folder named after its category."""
    roots, extra = set(), {}
    try:
        import models as model_mgr
        for s in model_mgr.model_status(models_dir, settings):
            p = s.get("located_path")
            if not (p and os.path.isfile(p)):
                continue
            d = os.path.dirname(os.path.abspath(p))
            sf = (s.get("dest_subfolder") or "").strip()
            if sf and os.path.basename(d).lower() == sf.lower():
                roots.add(os.path.dirname(d))          # <root>/<subfolder>/<file>
            elif sf:
                extra.setdefault(sf, set()).add(d)     # non-standard layout: register the exact dir
    except Exception as e:  # never let model scanning block engine startup
        print(f"[launcher] warning: could not scan located models: {e}")
    return roots, extra


def write_extra_model_paths(settings):
    """Point the engine at our app-managed models folder (fully decoupled from any other ComfyUI),
    plus the real folders of any located/overridden models so their basenames always resolve."""
    models_dir = os.path.join(ROOT, settings["models_dir"])
    yaml_path = os.path.join(ROOT, "config", "extra_model_paths.yaml")
    subfolders = ["checkpoints", "diffusion_models", "text_encoders", "clip", "vae",
                  "latent_upscale_models", "upscale_models", "loras", "unet"]
    lines = ["# Generated by launcher.py - do not edit by hand.", "chnmagicai:",
             f"  base_path: {models_dir.replace(os.sep, '/')}"]
    for sf in subfolders:
        lines.append(f"  {sf}: {sf}")

    # Additional search paths for located/overridden models (see _located_model_dirs). ComfyUI
    # accumulates every provider's paths per category, so these are purely additive.
    roots, extra = _located_model_dirs(models_dir, settings)
    for i, root in enumerate(sorted(roots)):
        if os.path.normpath(root) == os.path.normpath(models_dir):
            continue  # already the primary provider
        lines.append(f"chnmagicai_located{i}:")
        lines.append(f"  base_path: {root.replace(os.sep, '/')}")
        for sf in subfolders:
            lines.append(f"  {sf}: {sf}")
    j = 0
    for sf, dirs in sorted(extra.items()):
        for d in sorted(dirs):
            lines.append(f"chnmagicai_ovr{j}:")
            lines.append(f"  base_path: {d.replace(os.sep, '/')}")
            lines.append(f"  {sf}: .")
            j += 1

    with open(yaml_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return yaml_path


def resolve_python(settings):
    if settings.get("python_exe") and os.path.isfile(settings["python_exe"]):
        return settings["python_exe"]
    for cand in ("engine/python/Scripts/python.exe", "engine/python/bin/python3",
                 "engine/python/bin/python", "engine/python/python.exe"):
        p = os.path.join(ROOT, cand)
        if os.path.isfile(p):
            return p
    return sys.executable


def start_comfy(settings, python_exe, yaml_path):
    main_py = os.path.join(ROOT, settings["engine_dir"], "main.py")
    output_dir = os.path.join(ROOT, settings["output_dir"])
    os.makedirs(output_dir, exist_ok=True)
    cmd = [
        python_exe, main_py,
        "--listen", settings["comfy_host"],
        "--port", str(settings["comfy_port"]),
        "--output-directory", output_dir,
        "--extra-model-paths-config", yaml_path,
        "--disable-auto-launch",
    ]
    print("[launcher] starting engine:", " ".join(cmd))
    return subprocess.Popen(cmd, cwd=os.path.join(ROOT, settings["engine_dir"]))


def wait_ready(settings):
    sys.path.insert(0, os.path.dirname(__file__))
    import comfy_client
    client = comfy_client.ComfyClient(settings["comfy_host"], settings["comfy_port"])
    timeout = settings.get("comfy_startup_timeout_seconds", 300)
    print(f"[launcher] waiting for the engine to become ready...")
    return asyncio.run(client.wait_until_ready(timeout=timeout))


def open_browser_later(url, delay=1.5):
    def _open():
        time.sleep(delay)
        webbrowser.open(url)
    threading.Thread(target=_open, daemon=True).start()


def ensure_setup_and_relaunch():
    """Make direct `python backend/launcher.py` self-sufficient too.

    If the engine or its deps aren't ready, run the automatic bootstrap. Then, if we are not
    already running under the prepared engine interpreter, re-exec under it (so fastapi/uvicorn/
    torch are available). Guarded against infinite relaunch.
    """
    settings = load_settings()
    engine_main = os.path.join(ROOT, settings["engine_dir"], "main.py")
    needs_setup = (not os.path.isfile(engine_main)) or not (settings.get("python_exe") and os.path.isfile(settings["python_exe"]))
    if needs_setup and settings.get("setup", {}).get("auto", True):
        phase(5, "First-run setup: preparing the engine (this can take a while)...")
        sys.path.insert(0, os.path.dirname(__file__))
        import bootstrap
        bootstrap.main()
        settings = load_settings()

    target = resolve_python(settings)
    if os.environ.get("AIVB_RELAUNCHED") != "1" and os.path.abspath(target) != os.path.abspath(sys.executable):
        os.environ["AIVB_RELAUNCHED"] = "1"
        print(f"[launcher] switching to engine Python: {target}")
        return subprocess.call([target, os.path.abspath(__file__)], env=os.environ)
    return None


def main():
    relaunch = ensure_setup_and_relaunch()
    if relaunch is not None:
        return relaunch

    settings = load_settings()
    yaml_path = write_extra_model_paths(settings)
    python_exe = resolve_python(settings)

    phase(60, "Starting the video engine...")
    proc = start_comfy(settings, python_exe, yaml_path)
    try:
        if not wait_ready(settings):
            print("[launcher] ERROR: engine did not become ready in time.")
            phase(60, "Engine did not become ready in time.")
            proc.terminate()
            return 1
        print("[launcher] engine ready.")
        phase(92, "Engine ready. Starting the web server...")

        url = f"http://{settings['app_host']}:{settings['app_port']}/"
        if settings.get("open_browser", True):
            open_browser_later(url)
        print(f"[launcher] serving CHNMagicAI at {url}")
        phase(100, "Ready")

        sys.path.insert(0, os.path.dirname(__file__))
        import uvicorn
        uvicorn.run("app:app", host=settings["app_host"], port=settings["app_port"], log_level="info")
    finally:
        print("[launcher] shutting down engine...")
        proc.terminate()
        try:
            proc.wait(timeout=15)
        except Exception:
            proc.kill()
    return 0


if __name__ == "__main__":
    sys.exit(main())
